(() => {
  const cfg=window.QUAKEMESH_CONFIG||{}; const base=(cfg.apiBaseUrl||"http://127.0.0.1:8000").replace(/\/$/,"");
  const $=id=>document.getElementById(id); let map=null,layers=[],activeRunId=null;
  function ts(v){if(!v)return "—";return new Date(Number(v)).toLocaleTimeString()}
  async function get(path){const r=await fetch(base+path,{cache:"no-store"});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
  async function post(path,payload){const r=await fetch(base+path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok){const text=await r.text();throw new Error(`${r.status} ${text}`)}return r.json()}
  function initMap(){if(!window.L)return;map=L.map("map").setView([12.9716,77.5946],11);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map)}
  function drawEvent(e){if(!map)return;layers.forEach(x=>map.removeLayer(x));layers=[];const bounds=[];
    for(const p of e?.frontier_polygons||[]){const pts=p.boundary.map(x=>[x[0],x[1]]);const l=L.polygon(pts,{weight:1,fillOpacity:.08,dashArray:"4 4"}).addTo(map);layers.push(l);pts.forEach(x=>bounds.push(x))}
    for(const p of e?.footprint_polygons||[]){const pts=p.boundary.map(x=>[x[0],x[1]]);const l=L.polygon(pts,{weight:2,fillOpacity:.28}).addTo(map);layers.push(l);pts.forEach(x=>bounds.push(x))}
    if(bounds.length)map.fitBounds(bounds,{padding:[24,24],maxZoom:14});
  }
  function renderEvents(items){$("eventCount").textContent=items.length;$("confirmedCount").textContent=items.filter(x=>x.status==="CONFIRMED").length;
    $("eventsBody").innerHTML=items.map(e=>`<tr><td class="event-id">${e.event_id}</td><td><span class="status ${e.status}">${e.status}</span></td><td>${(e.device_ids||[]).length}</td><td>${(e.detection_footprint||[]).length}</td><td>${e.version}</td><td>${ts(e.updated_at_ms)}</td></tr>`).join("");
    const e=items[0]; if(!e){$("latest").className="empty";$("latest").textContent="No event yet.";return}
    $("latest").className="";$("latest").innerHTML=`<div class="event-id">${e.event_id}</div><p><span class="status ${e.status}">${e.status}</span></p><div class="kv"><div><span>Devices</span><strong>${(e.device_ids||[]).length}</strong></div><div><span>Footprint cells</span><strong>${(e.detection_footprint||[]).length}</strong></div><div><span>Frontier cells</span><strong>${(e.warning_frontier||[]).length}</strong></div><div><span>Version</span><strong>${e.version}</strong></div></div><div class="cells"><b>Detection Footprint</b><br>${(e.detection_footprint||[]).join(" · ")}</div>`;drawEvent(e)
  }
  function renderAlerts(items){$("alertCount").textContent=items.length;$("alertsBody").innerHTML=items.slice(0,100).map(a=>`<tr><td>${a.device_id||"—"}</td><td class="event-id">${a.event_id||"—"}</td><td>${a.event_version||"—"}</td><td>${a.status||"—"}</td><td>${ts(a.created_at_ms)}</td></tr>`).join("")}
  function renderRun(run){activeRunId=run.run_id;$("runId").textContent=run.run_id;$("runStatus").textContent=run.status;$("runExpected").textContent=run.expected_result||"—";$("runObserved").textContent=run.observed_result||"Waiting for evidence";$("runUpdated").textContent=ts(run.completed_at_ms||run.started_at_ms||run.created_at_ms);$("startScenario").disabled=["QUEUED","RUNNING"].includes(run.status);
    const stages=run.stages||[];const evaluations=stages.filter(s=>s.code==="CORRELATION_EVALUATED");const latest=evaluations[evaluations.length-1];const gateList=$("gateList");gateList.replaceChildren();
    if(!latest){gateList.className="gate-list empty";gateList.textContent="Waiting for correlation telemetry."}else{gateList.className="gate-list";const gates=[["Unique devices",latest.data.device_count,latest.data.required_devices],["Distinct H3 cells",latest.data.cell_count,latest.data.required_cells]];for(const [label,value,required] of gates){const row=document.createElement("div");const pass=Number(value)>=Number(required);row.className=`gate ${pass?"pass":"fail"}`;const name=document.createElement("span");name.textContent=label;const result=document.createElement("strong");result.textContent=`${value} / ${required} ${pass?"passed":"not met"}`;row.append(name,result);gateList.append(row)}}
    const timeline=$("timeline");timeline.replaceChildren();if(!stages.length){const li=document.createElement("li");li.className="empty";li.textContent="No stage telemetry yet.";timeline.append(li)}else{for(const stage of stages){const li=document.createElement("li");const time=document.createElement("time");time.textContent=ts(stage.occurred_at_ms);const title=document.createElement("strong");title.textContent=stage.code.replaceAll("_"," ");const message=document.createElement("p");message.textContent=stage.message;li.append(time,title,message);timeline.append(li)}timeline.scrollTop=timeline.scrollHeight}}
  async function refreshRun(){if(!activeRunId){const runs=await get("/v1/scenario-runs?limit=1");if(runs.items?.length)activeRunId=runs.items[0].run_id}if(activeRunId)renderRun(await get(`/v1/scenario-runs/${encodeURIComponent(activeRunId)}`))}
  async function refresh(){try{const [health,ev,al]=await Promise.all([get("/health"),get("/v1/events"),get("/v1/alerts")]);$("apiState").textContent="ONLINE";$("mode").textContent=cfg.modeLabel||health.mode||"ONLINE";$("mode").className="pill ok";$("connectionDetail").textContent=`Connected · ${new Date().toLocaleTimeString()}`;renderEvents(ev.items||ev.events||[]);renderAlerts(al.items||al.alerts||[]);await refreshRun();$("lastRefresh").textContent=`updated ${new Date().toLocaleTimeString()}`}catch(e){$("apiState").textContent="OFFLINE";$("mode").textContent="API OFFLINE";$("mode").className="pill bad";$("connectionDetail").textContent="Connection lost · retrying";console.error(e)}}
  $("scenarioForm").addEventListener("submit",async event=>{event.preventDefault();$("scenarioError").hidden=true;$("startScenario").disabled=true;try{const run=await post("/v1/demo/scenario-runs",{scenario:$("scenarioSelect").value,devices:Number($("deviceCount").value),seed:Number($("scenarioSeed").value),source:"dashboard"});activeRunId=run.run_id;renderRun(run)}catch(error){$("scenarioError").textContent=`Scenario could not start: ${error.message}`;$("scenarioError").hidden=false;$("startScenario").disabled=false}});
  initMap();refresh();setInterval(refresh,2000);
})();
